"""Tier 4 advanced features: forecasting, forward indexes, custom indexes, scenarios, compliance evidence, and support tickets."""

from __future__ import annotations

import datetime
from typing import Optional
from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Forecast(Base):
    """Nowcast and forecast predictions generated by quantitative models."""

    __tablename__ = "forecast"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    series_id: Mapped[str] = mapped_column(String(40), nullable=False, index=True)
    forecast_date: Mapped[datetime.date] = mapped_column(nullable=False, index=True)
    horizon_days: Mapped[int] = mapped_column(Integer, nullable=False)  # 7, 14, 30
    predicted_index: Mapped[float] = mapped_column(Float, nullable=False)
    lower_ci: Mapped[float] = mapped_column(Float, nullable=False)  # 95% Confidence Interval lower
    upper_ci: Mapped[float] = mapped_column(Float, nullable=False)  # 95% Confidence Interval upper
    model_name: Mapped[str] = mapped_column(String(50), default="ARIMA_EXPONENTIAL", nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class ForwardIndex(Base):
    """Forward-looking index for future departure dates."""

    __tablename__ = "forward_index"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    route_id: Mapped[str] = mapped_column(String(7), ForeignKey("ref_route.route_id"), nullable=False, index=True)
    travel_date: Mapped[datetime.date] = mapped_column(nullable=False, index=True)
    forward_index_value: Mapped[float] = mapped_column(Float, nullable=False)
    computed_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class CustomIndex(Base):
    """Tenant-defined custom basket or tailored weighting scheme."""

    __tablename__ = "custom_index"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    tenant_id: Mapped[int] = mapped_column(Integer, ForeignKey("tenant.id", ondelete="CASCADE"), nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    basket_config: Mapped[str] = mapped_column(Text, nullable=False)  # JSON configuration of routes & weights
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class Scenario(Base):
    """Booking savings simulator & policy scenario modeling."""

    __tablename__ = "scenario"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    tenant_id: Mapped[int] = mapped_column(Integer, ForeignKey("tenant.id", ondelete="CASCADE"), nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    parameters: Mapped[str] = mapped_column(Text, nullable=False)  # JSON policy parameters (e.g. shift L03 to L14)
    result_data: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # JSON savings calculations
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class ControlEvidence(Base):
    """Auditable evidence repository for regulatory compliance."""

    __tablename__ = "control_evidence"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    control_id: Mapped[str] = mapped_column(String(50), nullable=False, index=True)  # e.g. "CTRL-DATA-INTEGRITY-01"
    evidence_type: Mapped[str] = mapped_column(String(50), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    verified_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    verified_by: Mapped[str] = mapped_column(String(100), nullable=False)
    document_path: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)


class SupportTicket(Base):
    """Enterprise support and inquiry ticketing system."""

    __tablename__ = "support_ticket"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    tenant_id: Mapped[int] = mapped_column(Integer, ForeignKey("tenant.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
    subject: Mapped[str] = mapped_column(String(150), nullable=False)
    priority: Mapped[str] = mapped_column(String(20), default="MEDIUM", nullable=False)  # LOW, MEDIUM, HIGH, URGENT
    status: Mapped[str] = mapped_column(String(20), default="OPEN", nullable=False)  # OPEN, IN_PROGRESS, RESOLVED, CLOSED
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    messages: Mapped[list["TicketMessage"]] = relationship("TicketMessage", back_populates="ticket", cascade="all, delete-orphan")


class TicketMessage(Base):
    """Threaded conversation message within a support ticket."""

    __tablename__ = "ticket_message"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticket_id: Mapped[int] = mapped_column(Integer, ForeignKey("support_ticket.id", ondelete="CASCADE"), nullable=False, index=True)
    sender_id: Mapped[str] = mapped_column(String(80), nullable=False)
    sender_type: Mapped[str] = mapped_column(String(20), default="USER", nullable=False)  # USER, AGENT, SYSTEM
    message: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    ticket: Mapped["SupportTicket"] = relationship("SupportTicket", back_populates="messages")
